#!/bin/bash
#
# Output a Bash script setting installation-dependent environment variables
# for Carton build server
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

cat <<"EOF"
if [ -z "${_CARTON_ENV_SH+set}" ]; then
declare _CARTON_ENV_SH=

declare CARTON_LIB_DIR=`readlink -f \`dirname $0\`` # Replaced on installation
declare CARTON_DATA_DIR="."                         # Replaced on installation

PATH="$CARTON_LIB_DIR:$PATH"

fi #_CARTON_ENV_SH
EOF
