#!/bin/bash
#
# Build a commit distribution tarball
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

set -e -u -o pipefail -o noclobber
CARTON_ENV=`carton-env`
eval "$CARTON_ENV"

. carton.sh

if [ $# != 2 ]; then
    echo "Invalid number of arguments" >&2
    echo "Usage: `basename \"\$0\"` PROJECT_NAME COMMITTISH" >&2
    exit 1
fi
declare project_name="$1"
declare committish="$2"

if ! carton_name_is_valid "$project_name"; then
    echo "Invalid project name: $project_name" >&2
    exit 1
fi

carton_build_dist "$project_name" "$committish"
