#!/bin/bash
#
# Update local repo and build new commits
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

set -e -u -o pipefail -o noclobber

#
# Retrieve command-line arguments
#
declare package_name
declare remote_repo
declare local_repo
declare commit_repo
declare yum_repo

if [ $# != 5 ]; then
    echo "Invalid number of arguments" >&2
    echo "Usage: `basename \"\$0\"`" \
         "PACKAGE_NAME REMOTE_REPO LOCAL_REPO COMMIT_REPO YUM_REPO" >&2
    exit 1
fi

package_name="$1"; shift
remote_repo=`readlink -f "$1"`; shift
local_repo=`readlink -f "$1"`; shift
commit_repo=`readlink -f "$1"`; shift
yum_repo=`readlink -f "$1"`; shift

#
# Fetch new commits
#
declare commit_list
if ! [ -e "$local_repo" ]; then
    git init --quiet --bare "$local_repo"
fi
cd "$local_repo"
git fetch --quiet -- "$remote_repo"
if git show-ref --quiet refs/heads/last_build; then
    commit_list=`git log --format=format:%H last_build..FETCH_HEAD`
else
    commit_list=`git log --format=format:%H --reverse FETCH_HEAD`
fi

#
# Build new commits
#
mkdir -p "$commit_repo"
declare commit
for commit in $commit_list; do
    echo -n "Building $commit..." >&2
    rhqa-sssd-bs-build-commit "$package_name" "$local_repo" "$commit" \
                              "$commit_repo" "$yum_repo" &&
        echo "done." >&2 ||
        echo "failed." >&2
    git update-ref refs/heads/last_build "$commit"
done
