#!/bin/bash
#
# Publish commit RPM packages
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

set -e -u -o pipefail -o noclobber

# Publish commit RPM packages to a yum repo link.
# Args: commit_dir yum_link
function publish()
{
    declare commit_dir
    commit_dir=`readlink -f "$1"`; shift
    declare yum_link="$1"; shift
    declare -r rpmbuild_dir="$commit_dir/rpmbuild"
    declare -r new_yum_repo="$commit_dir/yum"
    declare -r new_yum_link="$commit_dir/yum.link"

    (
        shopt -s nullglob
        set -x
        mkdir "$new_yum_repo"
        # Copy current yum repo contents, if any
        for f in "$yum_link/"*; do
            echo "$f"
        done | xargs --no-run-if-empty cp -at "$new_yum_repo/"
        # Add this commit RPM packages
        find "$rpmbuild_dir"/{RPMS,SRPMS} -name "*.rpm" |
            xargs ln -sft "$new_yum_repo"
        # Update metadata
        createrepo --update "$new_yum_repo"
        # Replace link
        ln -s "$new_yum_repo" "$new_yum_link"
        mv -T "$new_yum_link" "$yum_link"
    ) > "$commit_dir/publish.log" 2>&1
    touch "$commit_dir/publish.stamp"
}

#
# Retrieve command-line arguments
#
if [ $# != 2 ]; then
    echo "Invalid number of arguments" >&2
    echo "Usage: `basename \"\$0\"` PROJECT_DIR COMMIT_HASH" >&2
    exit 1
fi

declare project_dir
declare commit_hash

project_dir=`readlink -f "$1"`; shift
commit_hash="$1"; shift

declare -r git_repo="$project_dir/git"
declare -r commit_repo="$project_dir/commit"
declare yum_link="$project_dir/yum"
declare commit_dir

cd "$git_repo"
# Normalize commit hash
commit_hash=`git log -n1 --format=format:%h "$commit_hash"`
commit_dir="$commit_repo/$commit_hash"

publish "$commit_dir" "$yum_link"
