#!/bin/bash
#
# Fetch project repos and publish new commit revisions
#
# Copyright (c) 2013 Red Hat, Inc. All rights reserved.
#
# This copyrighted material is made available to anyone wishing
# to use, modify, copy, or redistribute it subject to the terms
# and conditions of the GNU General Public License version 2.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

set -e -u -o pipefail -o noclobber
eval "`carton-env || echo false`"

if [ $# != 0 ] && [ $# != 1 ]; then
    echo "Invalid number of arguments" >&2
    echo "Usage: `basename \"\$0\"` [PROJECT]" >&2
    exit 1
fi

declare project_name_list
declare project_name

if (( $# > 0 )); then
    project_name="$1"; shift

    if ! carton_project_name_is_valid "$project_name"; then
        echo "Invalid project name: $project_name" >&2
        exit 1
    fi
    if ! carton_project_exists "$project_name"; then
        echo "Project doesn't exist: $project_name" >&2
        exit 1
    fi
    project_name_list="$project_name"
else
    project_name_list=`carton_project_list_list`
fi

for while read -r project_name; do
    declare -A project
    carton_project_list_get project "$project_name"
    carton_project_fetch project
    carton_project_update project
done <<<"$project_name_list"
